export const FARES_TABLES = [
  'advance_ticket',
  'easement_detail',
  'easement_exception',
  'easement_location',
  'easement_text',
  'easement_toc',
  'fare',
  'flow',
  'idms_fare_group_permitted_stations',
  'link',
  'location',
  'location_association',
  'location_group',
  'location_group_member',
  'location_railcard',
  'location_synonym',
  'log',
  'london_route',
  'london_station',
  'map',
  'network_flow_restriction',
  'new_station',
  'non_derivable_fare',
  'non_derivable_fare_override',
  'non_standard_discount',
  'package',
  'package_supplement',
  'permitted_route',
  'railcard',
  'railcard_minimum_fare',
  'restriction_date',
  'restriction_exception',
  'restriction_header',
  'restriction_header_date',
  'restriction_railcard',
  'restriction_ticket_calendar',
  'restriction_time',
  'restriction_time_date',
  'restriction_time_toc',
  'restriction_train',
  'restriction_train_date',
  'restriction_train_quota',
  'route',
  'route_data',
  'route_location',
  'routeing_node',
  'routeing_point',
  'rover',
  'rover_price',
  'station_cluster',
  'station_group',
  'station_link',
  'station_routeing_point',
  'status',
  'status_discount',
  'supplement',
  'supplement_override',
  'supplement_rule',
  'supplement_rule_applies',
  'supplement_rule_supplement',
  'ticket_type',
  'ticket_validity',
  'toc',
  'toc_fare',
  'toc_specific_ticket',
];

export const faresView = 'START TRANSACTION;' +
  'CREATE TABLE IF NOT EXISTS nfm64(id INT(6));' + // nfm64 is creted in separate process
  FARES_TABLES.map(j => `
  DROP TABLE IF EXISTS {orgdb}.${j};
  CREATE OR REPLACE VIEW {orgdb}.${j} AS SELECT * FROM {dbname}.${j};
  `).join('') +
  ' COMMIT;';